apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsession-cronjob
spec:
  startingDeadlineSeconds: 20
  schedule: "0 0 1 * *"
  jobTemplate:
    spec: 
      backoffLimit: 2
      ttlSecondsAfterFinished: 30
      template:
        spec:
          containers:
          - name: djangoapp 
            image: django_app
            imagePullPolicy: Never
            envFrom:
              - configMapRef:
                  name: django-config
            command: ["./manage.py"]
            args: ["clearsessions"]
          restartPolicy: OnFailure
