version: "3"

services:
  db:
    image: postgres:12.0-alpine
    platform: linux/arm64/v8
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: ./.env.k8s
    ports:
      - ${DATABASE_IP}:5432:5432

  web:
    build: backend_main_django
    image: django_app
    platform: linux/arm64/v8
    env_file: ./.env.k8s
    volumes:
      - ./backend_main_django:/code
    ports:
      - 127.0.0.1:8080:80
    depends_on:
      - db

volumes:
  db_data:
